version: '3.1'
volumes:
  addons:
  postgres-data:
services:
  web:
    platform: linux/amd64
    image: odoo:16.0
    depends_on:
      - db
    volumes:
      - addons:/mnt/extra-addons
    ports:
      - "8069:8069"
  db:
    platform: linux/amd64
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo